# <span  style="font-family:'New time Roman'; color:rgb(194,231,255) ;display:block; text-align:center;"> PROG1350A - Python III: Data Preprocessing and Statistical Analysis <br> Assignment I (Group Assignment) </br> Data Cleaning and Variable Encoding with Pandas </span>

### <span  style="font-family:'New time Roman'; color:rgb(224,233,235) ;display:block; text-align:right;">Prepared by : </br> Alphonse haba </br> Rasheedat Abdulazeez </span>

In [11]:
!pip install pandas -U -q

In [1]:
import numpy as np
import pandas as pd

In [2]:
churnDataset = pd.read_excel("C:/Users/Cetaking/Desktop/NBCC/second_module/Python3/customer_churn.xlsx")
churnDataset

,Customer ID,Churn Label,Account Length (in months),Local Calls,Local Mins,Intl Calls,Intl Mins,Intl Active,Intl Plan,Extra International Charges,...,Senior,Group,Number of Customers in Group,Device Protection & Online Backup,Contract Type,Payment Method,Monthly Charge,Total Charges,Churn Category,Churn Reason
0,4444-BZPU,No,1,3,8.0,0.0,0.0,No,no,0.0,...,No,No,0,No,Month-to-Month,Direct Debit,10,10,NaN,NaN
1,5676-PTZX,no,33,179,431.3,0.0,0.0,No,No,0.0,...,No,No,0,yes,One Year,Paper Check,21,703,NaN,NaN
2,8532-ZEKQ,No,44,82,217.6,0.0,0.0,No,yes,0.0,...,no,no,0,yes,One Year,Direct Debit,23,1014,NaN,NaN
3,1314-SMPJ,No,10,47,111.6,60.0,71.0,Yes,yes,0.0,...,no,No,0,No,Month-to-Month,Paper Check,17,177,NaN,NaN
4,2956-TXCJ,no,62,184,621.2,310.0,694.4,Yes,Yes,0.0,...,no,No,0,No,One Year,Direct Debit,28,1720,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6682,2940-QHVU,Yes,3,6,16.8,0.0,0.0,No,no,0.0,...,No,Yes,2,No,Month-to-Month,Paper Check,19,52,Competitor,Competitor offered higher download speeds
6683,3033-TMYG,Yes,1,7,15.0,0.0,0.0,No,no,0.0,...,No,Yes,3,Yes,Month-to-Month,Direct Debit,20,20,Competitor,Competitor offered higher download speeds
6684,7029-XDVM,Yes,6,20,46.9,0.0,0.0,No,no,0.0,...,No,Yes,6,yes,Month-to-Month,Paper Check,18,108,Competitor,Competitor made better offer
6685,6614-NAJG,Yes,3,6,15.4,0.0,0.0,No,no,0.0,...,No,Yes,5,No,Month-to-Month,Credit Card,15,46,Attitude,Attitude of support person
6686,5104-AGDX,Yes,1,7,15.0,0.0,0.0,No,No,0.0,...,No,yes,6,no,Month-to-Month,Direct Debit,9,9,Competitor,Competitor made better offer

# <span style="font-family:'New time roman';color:rgb(224,233,235);">  Inspecting the structure of our dataset:</span>
<span style="font-family:'New time roman';color:rgb(224,233,235);">
 1. find the numerical and categorical variables and theirs data types.</br>
 2. identify the number of columns and rows
</span>

In [3]:
churnDataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6687 entries, 0 to 6686
Data columns (total 29 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        6687 non-null   object
 1   Churn Label                        6687 non-null   object
 2   Account Length (in months)         6687 non-null   int64
 3   Local Calls                        6687 non-null   int64
 4   Local Mins                         6687 non-null   float64
 5   Intl Calls                         6687 non-null   float64
 6   Intl Mins                          6687 non-null   float64
 7   Intl Active                        6687 non-null   object
 8   Intl Plan                          6687 non-null   object
 9   Extra International Charges        6687 non-null   float64
 10  Customer Service Calls             6687 non-null   int64
 11  Avg Monthly GB Download            6687 non-null   int64
 12  Unlimited Data Plan                6687 non-null   object
 13  Extra Data Charges                 6687 non-null   int64
 14  State                              6687 non-null   object
 15  Phone Number                       6687 non-null   object
 16  Gender                             6687 non-null   object
 17  Age                                6687 non-null   int64
 18  Under 30                           6687 non-null   object
 19  Senior                             6687 non-null   object
 20  Group                              6687 non-null   object
 21  Number of Customers in Group       6687 non-null   int64
 22  Device Protection & Online Backup  6687 non-null   object
 23  Contract Type                      6687 non-null   object
 24  Payment Method                     6687 non-null   object
 25  Monthly Charge                     6687 non-null   int64
 26  Total Charges                      6687 non-null   int64
 27  Churn Category                     1769 non-null   object
 28  Churn Reason                       1769 non-null   object
dtypes: float64(4), int64(9), object(16)
memory usage: 1.5+ MB

In [4]:
churnDataset.shape

(6687, 29)

In [5]:
churnDataset.head()

,Customer ID,Churn Label,Account Length (in months),Local Calls,Local Mins,Intl Calls,Intl Mins,Intl Active,Intl Plan,Extra International Charges,...,Senior,Group,Number of Customers in Group,Device Protection & Online Backup,Contract Type,Payment Method,Monthly Charge,Total Charges,Churn Category,Churn Reason
0,4444-BZPU,No,1,3,8.0,0.0,0.0,No,no,0.0,...,No,No,0,No,Month-to-Month,Direct Debit,10,10,NaN,NaN
1,5676-PTZX,no,33,179,431.3,0.0,0.0,No,No,0.0,...,No,No,0,yes,One Year,Paper Check,21,703,NaN,NaN
2,8532-ZEKQ,No,44,82,217.6,0.0,0.0,No,yes,0.0,...,no,no,0,yes,One Year,Direct Debit,23,1014,NaN,NaN
3,1314-SMPJ,No,10,47,111.6,60.0,71.0,Yes,yes,0.0,...,no,No,0,No,Month-to-Month,Paper Check,17,177,NaN,NaN
4,2956-TXCJ,no,62,184,621.2,310.0,694.4,Yes,Yes,0.0,...,no,No,0,No,One Year,Direct Debit,28,1720,NaN,NaN

<span style="font-family:'New time roman; color:';"> # QUESTION 2: </br>
    2.Identify the number/percent of missing data per column. Decide whether any columns should be dropped based on these results and drop them if necessary. Additionally, drop any columns that you consider irrelevant for the project. Assume that unique identifiers are irrelevant for your analysis.

</span>

In [6]:
missing_value = churnDataset.isna().sum()
missing_value

Customer ID                             0
Churn Label                             0
Account Length (in months)              0
Local Calls                             0
Local Mins                              0
Intl Calls                              0
Intl Mins                               0
Intl Active                             0
Intl Plan                               0
Extra International Charges             0
Customer Service Calls                  0
Avg Monthly GB Download                 0
Unlimited Data Plan                     0
Extra Data Charges                      0
State                                   0
Phone Number                            0
Gender                                  0
Age                                     0
Under 30                                0
Senior                                  0
Group                                   0
Number of Customers in Group            0
Device Protection & Online Backup       0
Contract Type                           0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Churn Category                       4918
Churn Reason                         4918
dtype: int64

In [7]:
percentage_of_missingV = churnDataset.isna().mean() * 100
percentage_of_missingV

Customer ID                           0.000000
Churn Label                           0.000000
Account Length (in months)            0.000000
Local Calls                           0.000000
Local Mins                            0.000000
Intl Calls                            0.000000
Intl Mins                             0.000000
Intl Active                           0.000000
Intl Plan                             0.000000
Extra International Charges           0.000000
Customer Service Calls                0.000000
Avg Monthly GB Download               0.000000
Unlimited Data Plan                   0.000000
Extra Data Charges                    0.000000
State                                 0.000000
Phone Number                          0.000000
Gender                                0.000000
Age                                   0.000000
Under 30                              0.000000
Senior                                0.000000
Group                                 0.000000
Number of Customers in Group          0.000000
Device Protection & Online Backup     0.000000
Contract Type                         0.000000
Payment Method                        0.000000
Monthly Charge                        0.000000
Total Charges                         0.000000
Churn Category                       73.545686
Churn Reason                         73.545686
dtype: float64

In [8]:
new_churnDataset = churnDataset.copy()
new_churnDataset = new_churnDataset.drop(columns = ["Customer ID", "Churn Reason"])
new_churnDataset

,Churn Label,Account Length (in months),Local Calls,Local Mins,Intl Calls,Intl Mins,Intl Active,Intl Plan,Extra International Charges,Customer Service Calls,...,Under 30,Senior,Group,Number of Customers in Group,Device Protection & Online Backup,Contract Type,Payment Method,Monthly Charge,Total Charges,Churn Category
0,No,1,3,8.0,0.0,0.0,No,no,0.0,0,...,No,No,No,0,No,Month-to-Month,Direct Debit,10,10,NaN
1,no,33,179,431.3,0.0,0.0,No,No,0.0,0,...,no,No,No,0,yes,One Year,Paper Check,21,703,NaN
2,No,44,82,217.6,0.0,0.0,No,yes,0.0,0,...,No,no,no,0,yes,One Year,Direct Debit,23,1014,NaN
3,No,10,47,111.6,60.0,71.0,Yes,yes,0.0,0,...,No,no,No,0,No,Month-to-Month,Paper Check,17,177,NaN
4,no,62,184,621.2,310.0,694.4,Yes,Yes,0.0,0,...,No,no,No,0,No,One Year,Direct Debit,28,1720,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6682,Yes,3,6,16.8,0.0,0.0,No,no,0.0,0,...,No,No,Yes,2,No,Month-to-Month,Paper Check,19,52,Competitor
6683,Yes,1,7,15.0,0.0,0.0,No,no,0.0,5,...,Yes,No,Yes,3,Yes,Month-to-Month,Direct Debit,20,20,Competitor
6684,Yes,6,20,46.9,0.0,0.0,No,no,0.0,4,...,No,No,Yes,6,yes,Month-to-Month,Paper Check,18,108,Competitor
6685,Yes,3,6,15.4,0.0,0.0,No,no,0.0,2,...,No,No,Yes,5,No,Month-to-Month,Credit Card,15,46,Attitude
6686,Yes,1,7,15.0,0.0,0.0,No,No,0.0,1,...,Yes,No,yes,6,no,Month-to-Month,Direct Debit,9,9,Competitor

<span style="font-family:'New time roman; color:';"> # Answers: : </br>
Churn category and Churn reason columns have missing values in total :
    Churn Category : 4918 ( 73.5% )
    Churn reasn : 4918 ( 73.5% )
</span>

<span style="font-family:'New time roman; color:';"> # QUESTION 3 : </br>
Identify any data inconsistencies and fix them (e.g.: datatype conversion, string reformatting, invalid data, etc.).
</span>

In [9]:

columns = [
    "Churn Label", "Intl Plan", "Gender", "Under 30",
    "Senior", "Device Protection", "Contract Type",
    "Payment Method", "Churn Category", "Intl Active","Unlimited Data Plan",
    "State","Group"
]

for column in columns:
    if column in new_churnDataset.columns:
        print(f"{column}:{new_churnDataset[column].unique()}")

Churn Label:['No' 'no' 'Yes' 'yes']
Intl Plan:['no' 'No' 'yes' 'Yes']
Gender:['Female' 'male' 'Male' 'female' 'Prefer not to say']
Under 30:['No' 'no' 'yes' 'Yes']
Senior:['No' 'no' 'yes' 'Yes']
Contract Type:['Month-to-Month' 'One Year' 'Two Year']
Payment Method:['Direct Debit' 'Paper Check' 'Credit Card']
Churn Category:[nan 'Competitor' 'Other' 'Attitude' 'Dissatisfaction' 'Price']
Intl Active:['No' 'Yes' 'no']
Unlimited Data Plan:['Yes' 'yes' 'No' 'no']
State:['KS' 'OH' 'MO' 'WV' 'RI' 'IA' 'NY' 'ID' 'VT' 'TX' 'CO' 'SC' 'NE' 'IL'
 'NH' 'LA' 'AZ' 'OK' 'GA' 'MA' 'MD' 'AR' 'WI' 'OR' 'MI' 'WY' 'VA' 'CA'
 'MN' 'SD' 'WA' 'UT' 'NJ' 'NM' 'NV' 'DC' 'IN' 'KY' 'ME' 'MT' 'MS' 'AL'
 'FL' 'AK' 'DE' 'TN' 'NC' 'CT' 'PA' 'ND' 'HI']
Group:['No' 'no' 'Yes' 'yes']

In [10]:

columns = [
    "Churn Label", "Intl Plan", "Gender", "Under 30",
    "Senior", "Device Protection", "Contract Type",
    "Payment Method", "Churn Category", "Intl Active","Unlimited Data Plan",
    "State","Group"
]

for column in columns:
    if column in new_churnDataset.columns:
        new_churnDataset[column] = (
            new_churnDataset[column]
            .astype("string")
            .str.strip()
            .str.title()
        )

new_churnDataset.head()

,Churn Label,Account Length (in months),Local Calls,Local Mins,Intl Calls,Intl Mins,Intl Active,Intl Plan,Extra International Charges,Customer Service Calls,...,Under 30,Senior,Group,Number of Customers in Group,Device Protection & Online Backup,Contract Type,Payment Method,Monthly Charge,Total Charges,Churn Category
0,No,1,3,8.0,0.0,0.0,No,No,0.0,0,...,No,No,No,0,No,Month-To-Month,Direct Debit,10,10,<NA>
1,No,33,179,431.3,0.0,0.0,No,No,0.0,0,...,No,No,No,0,yes,One Year,Paper Check,21,703,<NA>
2,No,44,82,217.6,0.0,0.0,No,Yes,0.0,0,...,No,No,No,0,yes,One Year,Direct Debit,23,1014,<NA>
3,No,10,47,111.6,60.0,71.0,Yes,Yes,0.0,0,...,No,No,No,0,No,Month-To-Month,Paper Check,17,177,<NA>
4,No,62,184,621.2,310.0,694.4,Yes,Yes,0.0,0,...,No,No,No,0,No,One Year,Direct Debit,28,1720,<NA>

In [11]:
columns = [
    "Churn Label", "Intl Plan", "Gender", "Under 30",
    "Senior", "Device Protection", "Contract Type",
    "Payment Method", "Churn Category", "Intl Active","Unlimited Data Plan",
    "State","Group"
]
for i in columns:
    if i in new_churnDataset.columns:
        print(f"{i}:{new_churnDataset[i].unique()}")

Churn Label:<StringArray>
['No', 'Yes']
Length: 2, dtype: string
Intl Plan:<StringArray>
['No', 'Yes']
Length: 2, dtype: string
Gender:<StringArray>
['Female', 'Male', 'Prefer Not To Say']
Length: 3, dtype: string
Under 30:<StringArray>
['No', 'Yes']
Length: 2, dtype: string
Senior:<StringArray>
['No', 'Yes']
Length: 2, dtype: string
Contract Type:<StringArray>
['Month-To-Month', 'One Year', 'Two Year']
Length: 3, dtype: string
Payment Method:<StringArray>
['Direct Debit', 'Paper Check', 'Credit Card']
Length: 3, dtype: string
Churn Category:<StringArray>
[<NA>, 'Competitor', 'Other', 'Attitude', 'Dissatisfaction', 'Price']
Length: 6, dtype: string
Intl Active:<StringArray>
['No', 'Yes']
Length: 2, dtype: string
Unlimited Data Plan:<StringArray>
['Yes', 'No']
Length: 2, dtype: string
State:<StringArray>
['Ks', 'Oh', 'Mo', 'Wv', 'Ri', 'Ia', 'Ny', 'Id', 'Vt', 'Tx', 'Co', 'Sc', 'Ne',
 'Il', 'Nh', 'La', 'Az', 'Ok', 'Ga', 'Ma', 'Md', 'Ar', 'Wi', 'Or', 'Mi', 'Wy',
 'Va', 'Ca', 'Mn', 'Sd', 'Wa', 'Ut', 'Nj', 'Nm', 'Nv', 'Dc', 'In', 'Ky', 'Me',
 'Mt', 'Ms', 'Al', 'Fl', 'Ak', 'De', 'Tn', 'Nc', 'Ct', 'Pa', 'Nd', 'Hi']
Length: 51, dtype: string
Group:<StringArray>
['No', 'Yes']
Length: 2, dtype: string

<span style="font-family:'New time roman; color:';"> # QUESTION 4 </br>
Based on point 3, perform data inputting on the columns that require it. Optionally, you can remove rows with missing values.
</span>

In [12]:
new_churnDataset = new_churnDataset.dropna()
new_churnDataset.isna().mean() * 100

Churn Label                          0.0
Account Length (in months)           0.0
Local Calls                          0.0
Local Mins                           0.0
Intl Calls                           0.0
Intl Mins                            0.0
Intl Active                          0.0
Intl Plan                            0.0
Extra International Charges          0.0
Customer Service Calls               0.0
Avg Monthly GB Download              0.0
Unlimited Data Plan                  0.0
Extra Data Charges                   0.0
State                                0.0
Phone Number                         0.0
Gender                               0.0
Age                                  0.0
Under 30                             0.0
Senior                               0.0
Group                                0.0
Number of Customers in Group         0.0
Device Protection & Online Backup    0.0
Contract Type                        0.0
Payment Method                       0.0
Monthly Charge                       0.0
Total Charges                        0.0
Churn Category                       0.0
dtype: float64

<span style="font-family:'New time roman; color:';"> # QUESTION 5 </br>
Detect and remove duplicates if present. Identify potential outliers in your dataset and decide whether to keep or remove them.
</span>

In [13]:
new_churnDataset.duplicated().sum()

np.int64(0)

<span style="font-family:'New time roman; color:';"> # QUESTION 5 </br>
Encode categorical variables using One-Hot encoding or Label encoding (choose the most suitable method for each of the variables). Your resulting dataset should not include the original variables after the encoding process.
</span>

In [14]:
Contract_encoding_label = {
    "Month-To-Month":0,
    "One Year":1,
    "Two Year":2
}

new_churnDataset["Contract_label"] = new_churnDataset["Contract Type"].map(Contract_encoding_label)
new_churnDataset[["Contract Type","Contract_label"]]

C:\Users\Cetaking\AppData\Local\Temp\ipykernel_29836\4116556727.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_churnDataset["Contract_label"] = new_churnDataset["Contract Type"].map(Contract_encoding_label)

       Contract Type  Contract_label
3493  Month-To-Month               0
3494  Month-To-Month               0
3495  Month-To-Month               0
3496  Month-To-Month               0
3497  Month-To-Month               0
...              ...             ...
6682  Month-To-Month               0
6683  Month-To-Month               0
6684  Month-To-Month               0
6685  Month-To-Month               0
6686  Month-To-Month               0

[1769 rows x 2 columns]

In [15]:
new_churnDataset

,Churn Label,Account Length (in months),Local Calls,Local Mins,Intl Calls,Intl Mins,Intl Active,Intl Plan,Extra International Charges,Customer Service Calls,...,Senior,Group,Number of Customers in Group,Device Protection & Online Backup,Contract Type,Payment Method,Monthly Charge,Total Charges,Churn Category,Contract_label
3493,Yes,2,11,22.1,0.0,0.0,No,No,0.0,0,...,No,No,0,No,Month-To-Month,Credit Card,34,69,Competitor,0
3494,Yes,10,33,114.9,0.0,0.0,No,No,0.0,0,...,No,No,0,Yes,Month-To-Month,Credit Card,34,321,Competitor,0
3495,Yes,1,2,6.0,0.0,0.0,No,No,0.0,0,...,Yes,No,0,Yes,Month-To-Month,Direct Debit,15,15,Other,0
3496,Yes,1,8,15.0,0.0,0.0,No,No,0.0,0,...,No,No,0,No,Month-To-Month,Credit Card,11,11,Competitor,0
3497,Yes,1,7,15.0,264.0,811.8,Yes,No,162.4,0,...,No,No,0,No,Month-To-Month,Direct Debit,15,15,Competitor,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6682,Yes,3,6,16.8,0.0,0.0,No,No,0.0,0,...,No,Yes,2,No,Month-To-Month,Paper Check,19,52,Competitor,0
6683,Yes,1,7,15.0,0.0,0.0,No,No,0.0,5,...,No,Yes,3,Yes,Month-To-Month,Direct Debit,20,20,Competitor,0
6684,Yes,6,20,46.9,0.0,0.0,No,No,0.0,4,...,No,Yes,6,yes,Month-To-Month,Paper Check,18,108,Competitor,0
6685,Yes,3,6,15.4,0.0,0.0,No,No,0.0,2,...,No,Yes,5,No,Month-To-Month,Credit Card,15,46,Attitude,0
6686,Yes,1,7,15.0,0.0,0.0,No,No,0.0,1,...,No,Yes,6,no,Month-To-Month,Direct Debit,9,9,Competitor,0